### ISSUE TITLE
joinedParsers arg clash in nested select

### ISSUE THREAD

**Issue by rdunk** [romeerez/orchid-orm#108]
I've run into an issue (seems to be recently introduced?) when selecting two properties that share the same name/key where one is in a nested select. For example:

```ts
await db.parent.select({
  clash: (q) => q.clash, // e.g. belongsTo
  children: (q) => q.children.select('clash'), // e.g. a text column
});
```

Will produce an error like this

```
file:///foobar/node_modules/pqb/src/queryMethods/select.ts:229
  const parsers = (q.query.joinedParsers as JoinedParsers)[arg];
                           ^
TypeError: Cannot read properties of undefined (reading 'clash')
    at addParsersForSelectJoined (file:///foobar/node_modules/pqb/src/queryMethods/select.ts:229:28)
    at processSelectArg (file:///foobar/node_modules/pqb/src/queryMethods/select.ts:304:7)
    at file:///foobar/node_modules/pqb/src/queryMethods/select.ts:580:43
    at Array.map (<anonymous>)
    at Db._select (file:///foobar/node_modules/pqb/src/queryMethods/select.ts:580:29)
    at Proxy.select (file:///foobar/node_modules/pqb/src/queryMethods/select.ts:568:25)
    at children (file:///foobar/index.ts:74:31)
    at resolveSubQueryCallback (file:///foobar/node_modules/pqb/src/utils.ts:86:18)
    at processSelectArg (file:///foobar/node_modules/pqb/src/queryMethods/select.ts:318:15)
    at file:///foobar/node_modules/pqb/src/queryMethods/select.ts:580:43
```

I suspect there is some kind of reference to a previously added join that the nested select picks up on incorrectly?

Full minimal reproduction:

```ts
import { createBaseTable, orchidORM } from 'orchid-orm';

const BaseTable = createBaseTable();

class ParentTable extends BaseTable {
  readonly table = 'parent';

  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    clashId: t.uuid().foreignKey(() => ClashTable, 'id'),
  }));

  relations = {
    clash: this.belongsTo(() => ClashTable, {
      primaryKey: 'id',
      foreignKey: 'clashId',
    }),
    children: this.hasMany(() => ChildTable, {
      primaryKey: 'id',
      foreignKey: 'parentId',
    }),
  };
}

class ClashTable extends BaseTable {
  readonly table = 'clash';

  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
  }));
}

class ChildTable extends BaseTable {
  readonly table = 'child';

  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    clashId: t.uuid().foreignKey(() => ClashTable, 'id'),
    parentId: t.integer().foreignKey(() => ParentTable, 'id'),
    safe: t.string(1, 100),
    clash: t.string(1, 100),
  }));

  relations = {
    parent: this.belongsTo(() => ParentTable, {
      required: true,
      primaryKey: 'id',
      foreignKey: 'parentId',
    }),
  };
}

const db = orchidORM(
  {
    databaseURL: process.env.DATABASE_URL,
    log: true,
  },
  {
    parent: ParentTable,
    clash: ClashTable,
    child: ChildTable,
  },
);

// Works
await db.parent.select({
  clash: (q) => q.clash,
  children: (q) => q.children.select('safe'),
});

// TypeError: Cannot read properties of undefined (reading 'clash')
await db.parent.select({
  clash: (q) => q.clash,
  children: (q) => q.children.select('clash'),
});

await db.$close();
```

LMK if more information is needed.

**Comment by romeerez** [comment]
I see that column `clash` and the relation `clash` are somehow bothering each other, will try to fix this tomorrow.

**Comment by romeerez** [comment]
If you re-order them it's gonna work:

```ts
await db.parent.select({
  children: (q) => q.children.select('clash'),
  clash: (q) => q.clash,
});
```

**Comment by romeerez** [comment]
I thought that it would be a good idea to allow selecting a full record of a joined table with just a name:

```ts
await db.table
  .join('some', 'id', 'someId')
  .select('some')
```

But apparently, it wasn't that good because you can have a `some` column and the ORM will be confused, as well as a developer:

```
await db.table
  .join('some', 'id', 'someId')
  // db.table has a column called `some`, what should be selected here?
  .select('some')
```

When selecting a relation, it does a joining under the hood, so the `select` is also confused if you select a relation named `some` while having a column called `some`.

I published a change to resolve this: now when you want to select a full record, you need to specify a `.*`.

```ts
await db.table
  .join('some', 'id', 'someId')
  // Both the ORM and the developer can be sure this is about a joined table
  .select('some.*')
  // It is clearly a column
  .select('some')
```

This resolves the issue.

**Comment by rdunk** [comment]
Thanks so much for looking into it. I'm away for a few days but will update all my queries on Monday and confirm here when everything is working if that would be helpful. 👍

**Comment by rdunk** [comment]
Tested and all working as expected now, thanks again.
