### ISSUE TITLE
ReferenceError: TextEncoder is not defined in pq

### ISSUE THREAD

**Issue by thomask5** [romeerez/orchid-orm#136]
I am currently upgrading our code base form using orchid 1.9.27 to 1.12.3. In doing the upgrade, I seeing a Reference Error when running my unit tests.

`ReferenceError: TextEncoder is not defined`

Traceback
`
      at Object.<anonymous> (../shared/node_modules/orchid-orm/node_modules/pg/lib/crypto/utils.js:31:21)
      at Object.<anonymous> (../shared/node_modules/orchid-orm/node_modules/pg/lib/crypto/sasl.js:2:16)
      at Object.<anonymous> (../shared/node_modules/orchid-orm/node_modules/pg/lib/client.js:5:12)
      at Object.<anonymous> (../shared/node_modules/orchid-orm/node_modules/pg/lib/index.js:3:14)
      at Object.<anonymous> (../shared/node_modules/orchid-orm/node_modules/pqb/dist/index.js:4:10)
      at Object.<anonymous> (../shared/node_modules/orchid-orm/dist/index.js:3:11)
      at Object.<anonymous> (../shared/orm/db.ts:11:20)
`

I am using yarn as my package manager to install orchid-orm + dependencies and run unit tests

**Comment by romeerez** [comment]
Looks like this is not related to the ORM, as there is no references to the `TextEncoder`, but some internal error of the `pg`. Try updating `pg` version to the latest, and if it's already latest try downgrading a bit, let me know if this helps.

**Comment by thomask5** [comment]
Thanks, update, it seems it has to do with my testing environment with the fix here: https://github.com/brianc/node-postgres/pull/2981
