### ISSUE TITLE
rake db create fails if no Postgres user specified

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#147]
With DATABASE_URL having no username, `npm run db create` crashes:

```console
❯ pnpm dlx orchid-orm@latest

✔ Where would you like to install Orchid ORM? … /Users/semenov/tmp/rake-test
✔ Preferred type of returned timestamps: › string (as returned from db)
✔ Should I add a separate database for tests? … no
✔ Are you going to use Zod for validation? … no
✔ Do you want object factories for writing tests? … no
✔ Should I add demo tables? … no
✔ Let's add fast TS compiler swc? … no

...

❯ cat .env
DATABASE_URL=postgres://localhost/dbname?ssl=false

❯ pnpm run db create

> @ db /Users/semenov/tmp/rake-test
> ts-node src/db/dbScript.ts "create"

error: zero-length delimited identifier at or near """"
    at /Users/semenov/tmp/rake-test/node_modules/.pnpm/pg@8.11.2/node_modules/pg/lib/client.js:526:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async performQuery$1 (/Users/semenov/tmp/rake-test/node_modules/.pnpm/pqb@0.17.4/node_modules/pqb/src/adapter.ts:167:12)
    at async execute (/Users/semenov/tmp/rake-test/node_modules/.pnpm/rake-db@2.10.16/node_modules/rake-db/src/commands/createOrDrop.ts:21:11)
    at async createOrDrop (/Users/semenov/tmp/rake-test/node_modules/.pnpm/rake-db@2.10.16/node_modules/rake-db/src/commands/createOrDrop.ts:62:18)
    at async createDb (/Users/semenov/tmp/rake-test/node_modules/.pnpm/rake-db@2.10.16/node_modules/rake-db/src/commands/createOrDrop.ts:132:11)
    at async runCommand (/Users/semenov/tmp/rake-test/node_modules/.pnpm/rake-db@2.10.16/node_modules/rake-db/src/rakeDb.ts:39:13) {
  length: 111,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '32',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1192',
  routine: 'scanner_yyerror'
}
```

When I add username to DATABASE_URL, it starts working:

```console
❯ cat .env
DATABASE_URL=postgres://semenov@localhost/dbname?ssl=false

❯ pnpm run db create

> @ db /Users/semenov/tmp/rake-test
> ts-node src/db/dbScript.ts "create"

Database dbname successfully created
Created versions table
```

However, db migrate works normally even without username:

```console
❯ cat .env
DATABASE_URL=postgres://localhost/dbname?ssl=false

❯ pnpm run db migrate

> @ db /Users/semenov/tmp/rake-test
> ts-node src/db/dbScript.ts "migrate"
```

I believe all (or most) other Postgres tools work without explicit username so I think it should be supported in db create as well?

**Comment by romeerez** [comment]
I didn't know PG can work without a username. Sure, I'll update to support it.

**Comment by romeerez** [comment]
Fixed and published.

> I believe all (or most) other Postgres tools work without explicit username so I think it should be supported in db create as well?

Yes, all tests for all packages work fine without the username, I only had to update SQL code for creating a database.
