### ISSUE TITLE
Support bun

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#150]
I noticed that rake-db doesn't work with bun. The following happened with fresh `pnpm dlx orchid-orm@latest`:

```
❯ bun src/db/dbScript.ts migrate
[0.19ms] ".env"
56 |     delete result.logger;
57 |   }
58 |   if (!result.basePath || !result.dbScript) {
59 |     const filePath = getCallerFilePath();
60 |     if (!filePath) {
61 |       throw new Error(
                ^
error: Failed to determine path to db script. Please set basePath option of rakeDb
      at processRakeDbConfig (/Users/semenov/tmp/rake-test/node_modules/rake-db/dist/index.mjs:61:12)
      at rakeDb (/Users/semenov/tmp/rake-test/node_modules/rake-db/dist/index.mjs:3691:17)
      at /Users/semenov/tmp/rake-test/src/db/dbScript.ts:6:22
```

I updated `dbScript.ts` as follows:

```ts
import { rakeDb } from 'rake-db';
import { config } from './config';
import { BaseTable } from './baseTable';

export const change = rakeDb(config.database, {
  baseTable: BaseTable,
  basePath: __dirname,
  dbScript: 'dbScript.ts', // just hardcoded while testing
  migrationsPath: './migrations',
  import: (path) => import(path),
});
```

After doing so, it worked oddly:

```
❯ bun src/db/dbScript.ts reset
[0.08ms] ".env"
Database dbname was successfully dropped

❯ bun src/db/dbScript.ts create
[0.08ms] ".env"
Database dbname successfully created

❯ bun src/db/dbScript.ts migrate
[0.09ms] ".env"
```

With bun, `reset` only dropped the db, didn't recreate it and didn't run migrations. `create` worked. `migrate` silently crashed.

I traced the crash to:
https://github.com/romeerez/orchid-orm/blob/65cd221067c561697975f8c6173fcd8b84159c81/packages/qb/pqb/src/adapter.ts#L164

but didn't investigate farther.

---

For comparison, with ts-node (or vite-node) it worked normally:

```
❯ pnpm ts-node src/db/dbScript.ts migrate
Created versions table
(10.8ms) CREATE TABLE "post" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "text" text NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
)
(1.7ms) CREATE UNIQUE INDEX "post_title_idx" ON "post" ("title")
Migrated file:///Users/semenov/tmp/rake-test/src/db/migrations/20230804101832_createPost.ts
(6.3ms) CREATE TABLE "comment" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postId" integer NOT NULL REFERENCES "post"("id"),
  "text" text NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
)
(1.0ms) CREATE INDEX "comment_postId_idx" ON "comment" ("postId")
Migrated file:///Users/semenov/tmp/rake-test/src/db/migrations/20230804101833_createComment.ts
```

However, "normal" ORM code (running `await db.table.all()`) worked fine with bun as well.

**Comment by IlyaSemenov** [comment]
OK, I figured it. Apparently, bun doesn't wait for pending promises created in a sync call (`rakeDb(...)`). If I add this to the end of `dbScript.ts`:

```ts
await new Promise(resolve => setTimeout(resolve, 1000));
```

everything starts to work.

**Comment by IlyaSemenov** [comment]
OK, I discovered that I can do `await change.promise`. Nevermind. :)
