### ISSUE TITLE
Multiple use of testTransaction

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#152]
Currently, reusing `testTransaction` after closing is not possible:

```ts
await testTransaction.start(db)
await testTransaction.close(db)
await testTransaction.start(db)
```

Result:

```
(18.7ms) BEGIN
(0.9ms) ROLLBACK
(0.2ms) ROLLBACK
8592 |     if (!trx) {
8593 |       sql.text = `BEGIN${options.level ? ` ISOLATION LEVEL ${options.level}` : ""}${options.readOnly !== void 0 ? ` READ ${options.readOnly ? "ONLY" : "WRITE"}` : ""}${options.deferrable !== void 0 ? ` ${options.deferrable ? "" : "NOT "}DEFERRABLE` : ""}`;
8594 |       if (log)
8595 |         logData = log.beforeQuery(sql);
8596 |       try {
8597 |         const result = await this.q.adapter.transaction(sql, callback);
                                 ^
TypeError: this.q.adapter.transaction is not a function. (In 'this.q.adapter.transaction(sql, callback)', 'this.q.adapter.transaction' is undefined)
      at /Users/semenov/test/orchid/node_modules/pqb/dist/index.mjs:8597:29
      at transaction (/Users/semenov/test/orchid/node_modules/pqb/dist/index.mjs:8560:20)
      at /Users/semenov/test/orchid/node_modules/pqb/dist/index.mjs:10211:21
      at new Promise (:1:20)
      at start (/Users/semenov/test/orchid/node_modules/pqb/dist/index.mjs:10210:11)
      at /Users/semenov/test/orchid/packages/graphql/1.ts:6:6
```

Is there a real reason for the limitation, or this can be improved to allow multiple use?

* pqb@0.17.6

**Comment by romeerez** [comment]
It was a small bug, thanks for finding it, fixed and published.
