### ISSUE TITLE
rake redo executes changes in wrong order

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#161]
Rake's `redo` is supposed to rollback changes bottom-to-top then redo them top-to-bottom. Instead, it always works bottom-to-top, thus failing to re-create table `bar` in the below example:

```ts
change(async (db) => {
  await db.createTable("foo", (t) => ({
    id: t.identity().primaryKey(),
  }))
})

change(async (db) => {
  await db.createTable("bar", (t) => ({
    foo_id: t.identity().foreignKey("foo", "id").primaryKey(),
  }))
})
```

This works with `db down` + `db up`, but crashes with `db redo`:

```
❯ pnpm db redo

> @test/db@ db /Users/semenov/work/test/packages/db
> vite-node --script src/rake.ts "redo"

(2.2ms) DROP TABLE "bar"
(0.9ms) DROP TABLE "foo"
Rolled back file:///Users/semenov/work/test/packages/db/src/migrations/20230804101735_create_user.ts
(5.6ms) CREATE TABLE "bar" (
  "foo_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES "foo"("id")
) Error: relation "foo" does not exist
/Users/semenov/work/test/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526
          Error.captureStackTrace(err);
                ^

error: relation "foo" does not exist
    at /Users/semenov/work/test/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransactionAdapter.arrays [as silentArrays] (file:///Users/semenov/work/test/node_modules/.pnpm/pqb@0.18.2/node_modules/pqb/src/adapter.ts:222:12)
    at wrapWithLog (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/migration/migration.ts:1207:22)
    at createTable$1 (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/migration/createTable.ts:92:20)
    at /Users/semenov/work/test/packages/db/src/migrations/20230804101735_create_user.ts:19:2
    at file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/commands/migrateOrRollback.ts:143:13
    at Adapter.transaction (file:///Users/semenov/work/test/node_modules/.pnpm/pqb@0.18.2/node_modules/pqb/src/adapter.ts:122:18)
    at processMigration (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/commands/migrateOrRollback.ts:130:16)
    at migrateOrRollback (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/commands/migrateOrRollback.ts:78:15) {
  length: 101,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '436',
  routine: 'RangeVarGetRelidExtended'
}
```

* rake-db 2.10.31

**Comment by romeerez** [comment]
Fixed and published `rake-db`, thanks for catching!
