### ISSUE TITLE
rake down executes wrong migration with custom migration source

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#162]
Given the two migration files:

```ts
change(async (db) => {
  await db.createTable("user", (t) => ({
    id: t.identity().primaryKey(),
  }))
})
```

and

```ts
change(async (db) => {
  await db.createTable("order", (t) => ({
    id: t.identity().primaryKey(),
    user_id: t.identity().foreignKey("user", "id"),
  }))
})
```

and the dbscript:

```ts
import { rakeDb } from "rake-db"

import { BaseTable } from "./base"

const migrations = import.meta.glob("./migrations/*.ts")
console.log(migrations)

export const change = rakeDb(
  { databaseURL: '......' },
  {
    baseTable: BaseTable,
    migrationsPath: "./migrations",
    migrationsTable: "rakedb_migration",
    migrations,
  },
)

await change.promise
```

Then when I run `db reset` and `db down`, the down command wants to rollback the first migration instead of the second:

```
❯ pnpm db reset

> @test/db@ db /Users/semenov/work/test/packages/db
> vite-node --script src/rake.ts "reset"

{
  './migrations/20230804101735_create_user.ts': [Function: ./migrations/20230804101735_create_user.ts],
  './migrations/20230819135959_create_order.ts': [Function: ./migrations/20230819135959_create_order.ts]
}
Database test was successfully dropped
Database test successfully created
Created versions table
(2.6ms) CREATE TABLE "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
)
Migrated file:///Users/semenov/work/test/packages/db/src/migrations/20230804101735_create_user.ts
(2.1ms) CREATE TABLE "order" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL REFERENCES "user"("id")
)
Migrated file:///Users/semenov/work/test/packages/db/src/migrations/20230819135959_create_order.ts

❯ pnpm db down 

> @test/db@ db /Users/semenov/work/test/packages/db
> vite-node --script src/rake.ts "down"

{
  './migrations/20230804101735_create_user.ts': [Function: ./migrations/20230804101735_create_user.ts],
  './migrations/20230819135959_create_order.ts': [Function: ./migrations/20230819135959_create_order.ts]
}
(2.0ms) DROP TABLE "user" Error: cannot drop table "user" because other objects depend on it
/Users/semenov/work/test/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526
          Error.captureStackTrace(err);
                ^

error: cannot drop table "user" because other objects depend on it
    at /Users/semenov/work/test/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransactionAdapter.arrays [as silentArrays] (file:///Users/semenov/work/test/node_modules/.pnpm/pqb@0.18.2/node_modules/pqb/src/adapter.ts:222:12)
    at wrapWithLog (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/migration/migration.ts:1207:22)
    at createTable$1 (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/migration/createTable.ts:92:20)
    at /Users/semenov/work/test/packages/db/src/migrations/20230804101735_create_user.ts:13:2
    at file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/commands/migrateOrRollback.ts:143:13
    at Adapter.transaction (file:///Users/semenov/work/test/node_modules/.pnpm/pqb@0.18.2/node_modules/pqb/src/adapter.ts:122:18)
    at processMigration (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/commands/migrateOrRollback.ts:130:16)
    at migrateOrRollback (file:///Users/semenov/work/test/node_modules/.pnpm/rake-db@2.10.31/node_modules/rake-db/src/commands/migrateOrRollback.ts:78:15) {
  length: 260,
  severity: 'ERROR',
  code: '2BP01',
  detail: 'constraint order_user_id_fkey on table "order" depends on table "user"',
  hint: 'Use DROP ... CASCADE to drop the dependent objects too.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'dependency.c',
  line: '1195',
  routine: 'reportDependentObjects'
}
```

If I update the dbscript to not use custom migrations source:

```ts
export const change = rakeDb(
  { databaseURL: '......' },
  {
    baseTable: BaseTable,
    migrationsPath: "./migrations",
    migrationsTable: "rakedb_migration",
    import: (path) => import(path),
  },
)
```

then `db down` works:

```
❯ pnpm db down

> @test/db@ db /Users/semenov/work/test/packages/db
> vite-node --script src/rake.ts "down"

(1.7ms) DROP TABLE "order"
Rolled back file:///Users/semenov/work/test/packages/db/src/migrations/20230819135959_create_order.ts
```

I have this 100% reproducible, but I realise it could be caused by some side effect. Let me know if you can't reproduce, I will try to come up with a reproduction repo.

**Comment by romeerez** [comment]
Simply forgot to revert the array for a rollback.

Fixed and published.
