### ISSUE TITLE
db pull not working?

### ISSUE THREAD

**Issue by minkoonim** [romeerez/orchid-orm#275]
```
$ bun db/dbScript.ts pull

4430 |     }
4431 |   }
4432 |   if (table) {
4433 |     for (const it of data.constraints) {
4434 |       if (it.tableName !== table.name || it.schemaName !== table.schemaName || it.check || ((_h = it.references) == null ? void 0 : _h.columns.length) !== 1 || it.references.columns[0] !== item.name || checkIfIsOuterRecursiveFkey(data, table, it.references)) {

TypeError: null is not an object (evaluating '_h.columns.length')
      at dbColumnToAst (/home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:4435:133)
      at makeDbStructureColumnsShape (/home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:4384:27)
      at tableToAst (/home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:4273:12)
      at /home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:4136:14

Bun v1.1.10 (Linux x64)
error: script "db" exited with code 1
```

This is my first time using db pull command, 
dunno what's wrong with it,
I used all the same file structures and settings as I usually do

**Comment by minkoonim** [comment]
oops, wrong credentials, my bad.

**Comment by romeerez** [comment]
my favorite kind of issues :)

**Comment by romeerez** [comment]
apparently, a better error message should be displayed in such case
