### ISSUE TITLE
lost in many to many relations

### ISSUE THREAD

**Issue by minkoonim** [romeerez/orchid-orm#276]
I'm trying to make typical user - m2m - role - m2m - permission system,
and when I go db g,
I get below error message,
base table has snakecase set true,

```
{
  item: undefined,
  key: "perm_id",
}
113 | const versionToString = (config, version) => config.migrationId === "timestamp" ? `${version}` : `${version}`.padStart(config.migrationId.serial, "0");
114 | const columnTypeToSql = (item) => {
115 |   return item.data.isOfCustomType ? quoteNameFromString(item.toSQL()) : item.toSQL();
116 | };
117 | const getColumnName = (item, key, snakeCase) => {
118 |   console.log({item, key})
                                                                ^
TypeError: undefined is not an object (evaluating 'item.data')
      at getColumnName (/home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:118:59)
      at map (:1:11)
      at astToQueries$1 (/home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:206:3)
      at /home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:81:19
      at createTable (/home/minkoonim/hsadmin/node_modules/rake-db/dist/index.mjs:35:3)

Bun v1.1.10 (Linux x64)
error: script "db" exited with code 1
```

code is:
```
export type AdminAction = 'LIST' | 'CREATE' | 'DETAIL' | 'UPDATE' | 'DELETE' | 'ACTIVATE' | 'DEACTIVATE'
export const adminAction = ['LIST', 'CREATE', 'DETAIL', 'UPDATE', 'DELETE', 'ACTIVATE', 'DEACTIVATE'] as const

export type ActionScope = 'ALL' | 'SELF'
export const actionScope = ['ALL', 'SELF'] as const

export type Staff = Selectable<StaffTable>
export type StaffInsert = Insertable<StaffTable>
export type StaffUpdate = Updatable<StaffTable>
export type StaffQuery = Queryable<StaffTable>

export class StaffTable extends BaseTable {
  readonly table = 'user_staff'

  columns = this.setColumns(t => ({
    id: t.id(),
    userId: t.integer().foreignKey(
      () => UserTable,
      'id',
      { onDelete: 'CASCADE', onUpdate: 'RESTRICT' },
    ).index(),
  }))

  relations = {
    user: this.belongsTo(() => UserTable, {
      required: true,
      columns: ['userId'],
      references: ['id'],
    }),

    roles: this.hasAndBelongsToMany(() => RoleTable, {
      columns: ['id'],
      references: ['staffId'],
      through: {
        table: 'user_staff_to_role',
        columns: ['roleId'],
        references: ['id'],
      },
    }),
  }
}

export type Role = Selectable<RoleTable>
export type RoleInsert = Insertable<RoleTable>
export type RoleUpdate = Updatable<RoleTable>
export type RoleQuery = Queryable<RoleTable>

export class RoleTable extends BaseTable {
  readonly table = 'user_staff_role'

  columns = this.setColumns(t => ({
    id: t.id(),
    name: t.varchar().unique(),
  }))

  relations = {
    staffs: this.hasAndBelongsToMany(() => StaffTable, {
      columns: ['id'],
      references: ['roleId'],
      through: {
        table: 'user_staff_to_role',
        columns: ['staffId'],
        references: ['id'],
      },
    }),

    permissions: this.hasAndBelongsToMany(() => PermissionTable, {
      columns: ['id'],
      references: ['roleId'],
      through: {
        table: 'user_role_to_perm',
        columns: ['permId'],
        references: ['id'],
      },
    }),
  }
}

export type Permission = Selectable<PermissionTable>
export type PermissionInsert = Insertable<PermissionTable>
export type PermissionUpdate = Updatable<PermissionTable>
export type PermissionQuery = Queryable<PermissionTable>

export class PermissionTable extends BaseTable {
  readonly table = 'user_staff_perm'

  columns = this.setColumns(t => ({
    id: t.id(),
    action: t.enum('AdminAction', adminAction),
    scope: t.enum('ActionScope', actionScope),
  }))

  relations = {
    roles: this.hasAndBelongsToMany(() => RoleTable, {
      columns: ['id'],
      references: ['permId'],
      through: {
        table: 'user_role_to_perm',
        columns: ['roleId'],
        references: ['id'],
      },
    }),
  }
}
```

**Comment by romeerez** [comment]
Thanks for the detailed input, I reproduced this, will fix

**Comment by romeerez** [comment]
I published a fix, update orchid-orm and please confirm if it works for you.
