### ISSUE TITLE
Error while generating migration; renaming column

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#309]
I'm trying to generate a new migration  with `npm run db g` and run into the following error:

```
✔ Create or rename start column from another column? Use arrows or jk. Press enter to submit.
  + start               create column
❯ ~ startTime => start  rename column
  ~ endTime => start    rename column

✔ Create or rename end column from another column? Use arrows or jk. Press enter to submit.
  + end             create column
❯ ~ endTime => end  rename column

[redacted]\node_modules\rake-db\src\generate\structureToAst.ts:204
  if (item.type === 'int2' || item.type === 'int4' || item.type === 'int8') {
           ^


TypeError: Cannot read properties of undefined (reading 'type')
    at getDbColumnIsSerial ([redacted]\node_modules\rake-db\src\generate\structureToAst.ts:204:12)
    at Object.instantiateDbColumn ([redacted]\node_modules\rake-db\src\generate\structureToAst.ts:229:20)
    at changeColumns ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\columns.generator.ts:237:22)
    at processColumns ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\columns.generator.ts:60:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at processTableChange ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\tables.generator.ts:419:9)
    at applyChangeTables ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\tables.generator.ts:235:11)
    at processTables ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\tables.generator.ts:100:9)
    at composeMigration ([redacted]\node_modules\orchid-orm\src\migrations\generate\composeMigration.ts:52:9)
    at generate ([redacted]\node_modules\orchid-orm\src\migrations\generate\generate.ts:105:21)

Node.js v20.5.0
```

**Comment by romeerez** [comment]
I can't debug without code, but this may be related to snake case and may be solved by the recent update.

If it's still broken, please give me some code for reproducing.

**Comment by mordechaim** [comment]
I updated to 1.32.0 indeed the above error went away, but now I have a new error:

```
C:\Users\morde\workspace\orchid-repro\node_modules\pg\lib\client.js:526
          Error.captureStackTrace(err)
                ^

error: syntax error at or near ","
    at C:\Users\morde\workspace\orchid-repro\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransactionAdapter.arrays (C:\Users\morde\workspace\orchid-repro\node_modules\pqb\src\adapter.ts:249:12)
    at changeTable (C:\Users\morde\workspace\orchid-repro\node_modules\rake-db\src\migration\changeTable.ts:339:20)
    at async eval (eval at verifyMigration (file:///C:/Users/morde/workspace/orchid-repro/node_modules/orchid-orm/dist/migrations.mjs:1911:23), <anonymous>:5:3)
    at adapter.transaction.text (C:\Users\morde\workspace\orchid-repro\node_modules\orchid-orm\src\migrations\generate\verifyMigration.ts:40:15)
    at Adapter.transaction (C:\Users\morde\workspace\orchid-repro\node_modules\pqb\src\adapter.ts:142:18)
    at generate (C:\Users\morde\workspace\orchid-repro\node_modules\orchid-orm\src\migrations\generate\generate.ts:121:20)
    at runCommand (C:\Users\morde\workspace\orchid-repro\node_modules\rake-db\src\rakeDb.ts:155:11) {
  length: 90,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '58',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1241',
  routine: 'scanner_yyerror'
}
```

Will post repro very soon

**Comment by mordechaim** [comment]
It's worth pointing out, it only happens when I change 2 columns in the same migration

**Comment by mordechaim** [comment]
[Here you go](https://github.com/mordechaim/orchid-repro).

Try running `npm run db g` and choosing to rename the columns

**Comment by mordechaim** [comment]
You're free to do anything with this database, I'll delete it after this issue is fixed.

**Comment by romeerez** [comment]
Thank you for a great repro with a ready to use db!

I found the reason, it turns out that Postgres doesn't support multiple column renames inside one ALTER TABLE, fixing.

**Comment by romeerez** [comment]
Published a fix, and it works fine, outputs a migration:

```ts
import { change } from '../dbScript';

change(async (db) => {
  await db.changeTable('user', (t) => ({
    firstName: t.rename('first'),
    lastName: t.rename('last'),
  }));
});
```

I didn't apply it to your db.
