### ISSUE TITLE
Migration generation fails when table contains SQL computed field

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#315]
My `User` table definition is as follows:

```ts
import { Selectable } from 'orchid-orm'
import { BaseTable } from '../baseTable'

export type User = Selectable<UserTable> & { name: string }

export class UserTable extends BaseTable {
    readonly table = 'account_user'

    columns = this.setColumns(t => ({
        id: t.identity().primaryKey(),
        firstName: t.text(),
        lastName: t.text(),
        email: t.text().unique(),
        password: t.text()
    }))

    computed = this.setComputed(q => ({
        name: q.sql`${q.column('firstName')} || ' ' || ${q.column('lastName')}`.type(t => t.string())
    }))
}
```

The computed field was added after the original table was already created, and it already has records. 
In theory adding a computed field doesn't even need a migration, but by simply adding the computed field I get the following error next time I try running `npm run db g`

```
[redacted]\node_modules\pg\lib\client.js:526
          Error.captureStackTrace(err)
                ^

error: column "name" of relation "account_user" contains null values
    at[redacted]\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransactionAdapter.arrays ([redacted]\node_modules\pqb\src\adapter.ts:249:12)
    at changeTable ([redacted]\node_modules\rake-db\src\migration\changeTable.ts:358:20)
    at async eval (eval at verifyMigration ([redacted]\node_modules\orchid-orm\dist\migrations.js:1912:23), <anonymous>:5:3)
    at adapter.transaction.text ([redacted]\node_modules\orchid-orm\src\migrations\generate\verifyMigration.ts:40:15)
    at Adapter.transaction ([redacted]\node_modules\pqb\src\adapter.ts:142:18)
    at generate ([redacted]\node_modules\orchid-orm\src\migrations\generate\generate.ts:121:20)
    at runCommand ([redacted]\node_modules\rake-db\src\rakeDb.ts:155:11) {
  length: 152,
  severity: 'ERROR',
  code: '23502',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'account_user',
  column: 'name',
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '6042',
  routine: 'ATRewriteTable'
}

Node.js v20.5.0
```

JS computed fields don't suffer from this.

I'm using OrchidORM 1.32.7

**Comment by romeerez** [comment]
I published a fix, this one was simple: just ignoring the computed sql columns.
