### ISSUE TITLE
Migration generation fails when changing identity to ALWAYS

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#316]
I want to update all primary keys on existing tables to use `GENERATED ALWAYS AS IDENTITY`. I change the identity definition as `identity({ always: true })` and then try to generate a migration. I get the following error:

```
[redacted]\node_modules\pg\lib\client.js:526
          Error.captureStackTrace(err)
                ^

error: multiple primary keys for table "account_user" are not allowed
    at [redacted]\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransactionAdapter.arrays ([redacted]\node_modules\pqb\src\adapter.ts:249:12)
    at changeTable ([redacted]\node_modules\rake-db\src\migration\changeTable.ts:358:20)
    at async eval (eval at verifyMigration ([redacted]\node_modules\orchid-orm\dist\migrations.js:1912:23), <anonymous>:5:3)
    at adapter.transaction.text ([redacted]\node_modules\orchid-orm\src\migrations\generate\verifyMigration.ts:40:15)
    at Adapter.transaction ([redacted]\node_modules\pqb\src\adapter.ts:142:18)
    at generate ([redacted]\node_modules\orchid-orm\src\migrations\generate\generate.ts:121:20)
    at runCommand ([redacted]\node_modules\rake-db\src\rakeDb.ts:155:11) {
  length: 129,
  severity: 'ERROR',
  code: '42P16',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '223',
  routine: 'index_check_primary_key'
}

Node.js v20.5.0
```

**Comment by romeerez** [comment]
I published a fix, and have found other problems along the way, so this should become more stable now.
