### ISSUE TITLE
Migration generation fails when table has a foreign key

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#348]
I created 2 tables, `a` and `b`, `b` references `a` and has a foreign key set on it. I generate a migration the first time, all goes well. Then I make a change to `a`, and try to generate a migration again, but it fails:

```shell
[redacted]\node_modules\pg\lib\client.js:526
          Error.captureStackTrace(err)
                ^

error: constraint "b_aId_fkey" for relation "b" already exists
    at [redacted]\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransactionAdapter.arrays ([redacted]\node_modules\pqb\src\adapter.ts:249:12)
    at changeTable ([redacted]\node_modules\rake-db\src\migration\changeTable.ts:358:20)
    at async eval (eval at verifyMigration ([redacted]/node_modules/orchid-orm/dist/migrations.mjs:2096:23), <anonymous>:9:3)
    at adapter.transaction.text ([redacted]\node_modules\orchid-orm\src\migrations\generate\verifyMigration.ts:40:15)
    at Adapter.transaction ([redacted]\node_modules\pqb\src\adapter.ts:142:18)
    at generate ([redacted]\node_modules\orchid-orm\src\migrations\generate\generate.ts:121:20)
    at runCommand ([redacted]\node_modules\rake-db\src\rakeDb.ts:155:11) {
  length: 123,
  severity: 'ERROR',
  code: '42710',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '8909',
  routine: 'ATExecAddConstraint'
}
```

I created a reproduction, with a prepared database to see it in action. You're free to do anything with the database, I'll delete it after this is fixed.

Try running `npm run db g`

https://github.com/mordechaim/orchid-fkey

**Comment by romeerez** [comment]
Thanks for the reproduction, it helped.

I published a fix for this.
