### ISSUE TITLE
Type cast to MONEY fails if value is null

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#353]
I'm querying a money field with raw SQL which might result in NULL.

Hypothetical scenario:
```ts
const value = await db.a.find(1).select({
    money: (q) => q.sql`NULL`.type((t) => t.money().nullable()),
});
```

It crashes with:

```
[redacted]\node_modules\pqb\src\columns\string.ts:321
      return parseFloat((input as string).replace(/,/g, '').replace(/\$/g, ''));


TypeError: Cannot read properties of null (reading 'replace')
    at Object.MoneyColumn.parseFn.Object.assign.hideFromCode ([redacted]\node_modules\pqb\src\columns\string.ts:321:43)
    at parseRecord ([redacted]\node_modules\pqb\src\queryMethods\then.ts:563:49)
    at then ([redacted]\node_modules\pqb\src\queryMethods\then.ts:236:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error
      at Db.getThen ([redacted]\node_modules\pqb\src\queryMethods\then.ts:83:18)
      at seed ([redacted]\src\db\seed.ts:16:35)
      at runCommand ([redacted]\node_modules\rake-db\src\rakeDb.ts:155:11)
```

Other string types, such as date or time seem to work just fine

**Comment by mordechaim** [comment]
I actually notice now that `money` is discouraged by Postgres

**Comment by mordechaim** [comment]
While I'm at it, I tried using the `numeric` type for my money fields, but I can no longer call the `sum` aggregate function, typescript complains (redacted table names):

```
Argument of type '"amount"' is not assignable to parameter of type 'SelectableOrExpressionOfType<{ relations: { a: RelationQuery<BelongsToInfo<"a", "aId", true, BelongsToQuery<TableToDb<ATable, { b: RelationQuery<HasManyInfo<ATable, "b", { relations: { role: RelationQuery<BelongsToInfo<...>, BelongsToParams<...>, true, true>;
```

🤷‍♂️

**Comment by IlyaSemenov** [comment]
You can use this to have numeric in the database and numbers on the JS side:

```ts
money: () => t.numeric().encode((n: number) => String(n)).parse((s: string) => Number(s)).as(t.real()),
```

(or just use `t.real()` or `t.doublePrecision()` right away if you don't care about loss of precision).

**Comment by IlyaSemenov** [comment]
@mordechaim:

For ad-hoc queries, this works:

```ts
const user = await db.user.find(1).select({
  money: q => q.sql`NULL`.type(t => t.real().nullable()),
})

console.log(user.money) // null (type is number | null)
```

For retrieving numbers from `numeric` table columns, use this:

```ts
class UserTable extends BaseTable {
  readonly table = "user"

  columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    name: t.varchar(),
    // Convert from numbers to strings and back. Type as if it were a t.real() column.
    balance: t.numeric().encode((n: number) => String(n)).parse((s: string) => Number(s)).as(t.real()),
  }))
}

// Use numbers for values
await db.user.insertMany([
  { name: "Alice", balance: 10 },
  { name: "Bob", balance: 20 },
])

// Retrieve sum as a number
const sum = await db.user.all().sum("balance")
console.log(sum) // 30 (type is number | null)
```

That said, despite the workarounds, the original issue that you opened is still relevant and should be fixed.

**Comment by romeerez** [comment]
Confirming a bug: `money` and `array` are currently failing at `NULL` values

**Comment by romeerez** [comment]
Published a fix for money and also array types to not fail on nulls.
