### ISSUE TITLE
q => q.rel.sum().transform() crashes

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#389]
Given a database where each User has several Accounts, the query involving an aggregate and transform on it crashes:

```ts
await db.user.select("id", "name", {
  balance: q => q.accounts.sum("balance").transform(x => Number(x) * 100),
})
```

The result is properly typed, but the query crashes in runtime:

```ts
(0.5ms) SELECT "user"."id", "user"."name", "balance".r "balance" FROM "user" LEFT JOIN LATERAL (SELECT sum("accounts"."balance") r FROM "account" AS "accounts" WHERE "accounts"."user_id" = "user"."id") "balance" ON true
/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/common/queryResultProcessing.ts:11
      item.parent[item.key] = applyTransforms(
                              ^


TypeError: Cannot set properties of undefined (setting 'undefined')
    at applyBatchTransforms (/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/common/queryResultProcessing.ts:11:31)
    at Object.fn (/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/select.ts:525:13)
    at parseBatch (/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:579:26)
    at Object.handleResult (/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:465:23)
    at then (/Users/is/work/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:237:22)
```

+ orchid-orm 1.35.5

Just in case, it doesn't have to do with `Number(...)` cast, mere `.transform(x => x)` crashes the same way.

Interestingly, it works correctly when not in a subquery:

```ts
await db.user.insert({ name: "Alice", accounts: { create: [{ balance: 10 }, { balance: 20 }] } })

console.log(await db.account.sum("balance").transform(x => Number(x) * 100))
// 3000
```

<details>
<summary>Full reproduction</summary>

```ts
import process from "node:process"

import { createBaseTable, orchidORM, testTransaction } from "orchid-orm"

const BaseTable = createBaseTable({ snakeCase: true })

class UserTable extends BaseTable {
  override readonly table = "user"

  override columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    name: t.varchar(),
  }))

  relations = {
    accounts: this.hasMany(() => AccountTable, {
      columns: ["id"],
      references: ["userId"],
    }),
  }
}

class AccountTable extends BaseTable {
  override readonly table = "account"

  override columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    userId: t.integer().foreignKey("user", "id"),
    balance: t.decimal(),
  }))
}

const db = orchidORM(
  { databaseURL: process.env.DATABASE_URL, log: true },
  {
    user: UserTable,
    account: AccountTable,
  },
)

await testTransaction.start(db)

await db.$query`
create table "user" (
  id serial primary key,
  name varchar not null
);
create table "account" (
  id serial primary key,
  user_id int not null references "user" (id),
  balance decimal not null
);`

// Works, no type error.
await db.user.insert({ name: "Alice", accounts: { create: [{ balance: 10 }, { balance: 20 }] } })

console.log(await db.account.sum("balance").transform(x => Number(x) * 100))
// 3000

const users = await db.user.select("id", "name", {
  balance: q => q.accounts.sum("balance").transform(x => Number(x) * 100),
})
// users is properly typed as { id: number, name: string, balance: number }[]
// but this crashes in runtime

await testTransaction.close(db)
```
</details>

**Comment by romeerez** [comment]
Thanks for such a detailed report!

I published a fix.

In your sample, `x` is already parsed to number but it can be `null` if there are no accounts.
Funnily enough, `Number(x)` handles that - defaults null to 0.

```ts
await db.user.select("id", "name", {
  balance: q => q.accounts.sum("balance").transform(x => Number(x) * 100),
})
```
