### ISSUE TITLE
FEATURE REQUEST:Handle it better when a column has an uknown type

### ISSUE THREAD

**Issue by capaj** [romeerez/orchid-orm#39]
When running db pull on a project which uses citext I got this:
 ```
$ ts-node src/db/dbScripts.ts pull
/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/structureToAst.ts:259
        throw new Error(
              ^
Error: Cannot handle column official.email_prefs.email: column type `citext` is not supported
    at pushTableAst (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/structureToAst.ts:259:15)
    at structureToAst (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/structureToAst.ts:92:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pullDbStructure (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/pull.ts:15:15)
    at async rakeDb (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/rakeDb.ts:33:7)
error Command failed with exit code 1.
```

**Comment by romeerez** [comment]
Done, now when some type is not officially supported, it will dump existing db column into:

```ts
await db.createTable('table', (t) => ({
  colName: t.type('citext'),
}))
```

It's enough for the migration, but in ORM table such `t.type('citext')` will have a TS type `unknown`, so you need to use `as` to tell to ORM that this is a text type:

```ts
class Table extends BaseTable {
  readonly table = 'table'
  columns = this.setColumns((t) => ({
    colName: t.type('citext').as(t.text()), // <-- .as(t.text()) here
  }))
}
```

**Comment by romeerez** [comment]
Added support for `citext`: [link to docs](https://orchid-orm.netlify.app/guide/columns-types.html#citext)
