### ISSUE TITLE
Support db.table.whereExists(q => q.rel)

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#395]
I propose to support this syntax:

```ts
// users with any accounts
await db.user.whereExists(q => q.accounts)

// users with accounts with positive balance
await db.user.whereExists(q => q.accounts.where({ balance: { gt: 0 } }))
```

This reads very natural and in line with the rest of the ORM, and **it's already allowed by typings**. It crashes in runtime though:

```
/Users/is/work/node_modules/.pnpm/pqb@0.40.3/node_modules/pqb/src/queryMethods/join/processJoinArgs.ts:131
        q.q.joinedShapes
            ^


TypeError: Cannot read properties of undefined (reading 'joinedShapes')
    at processJoinArgs (/Users/is/work/node_modules/.pnpm/pqb@0.40.3/node_modules/pqb/src/queryMethods/join/processJoinArgs.ts:131:13)
    at existsArgs (/Users/is/work/node_modules/.pnpm/pqb@0.40.3/node_modules/pqb/src/queryMethods/where/where.ts:352:20)
    at _queryWhereExists (/Users/is/work/node_modules/.pnpm/pqb@0.40.3/node_modules/pqb/src/queryMethods/where/where.ts:374:5)
    at Db.whereExists (/Users/is/work/node_modules/.pnpm/pqb@0.40.3/node_modules/pqb/src/queryMethods/where/where.ts:1072:12)
    at <anonymous> (/Users/is/work/1.ts:59:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

+ orchid-orm 1.35.8

**Comment by romeerez** [comment]
Ready, published
