### ISSUE TITLE
rake-db (postgres): db pull throws error on specific foreign key

### ISSUE THREAD

**Issue by lithdew** [romeerez/orchid-orm#41]
```console
file:///Users/dew/node_modules/orchid-core/src/utils.ts:125
  return `'${s.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
               ^
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at singleQuote (file:///Users/dew/node_modules/orchid-core/src/utils.ts:125:16)
    at foreignKeyArgsToCode (file:///Users/dew/node_modules/pqb/src/columns/code.ts:224:9)
    at foreignKeyToCode (file:///Users/dew/node_modules/pqb/src/columns/code.ts:197:34)
    at createTable (file:///Users/dew/node_modules/rake-db/src/pull/astToMigration.ts:188:15)
    at astToMigration (file:///Users/dew/node_modules/rake-db/src/pull/astToMigration.ts:41:19)
    at pullDbStructure (file:///Users/dew/node_modules/rake-db/src/pull/pull.ts:25:18)
```

Adding a `console.log(foreignKey)` at `foreignKeyArgsToCode` yields the following output:

```js
{
  columns: [ 'avatar_storage_id', 'avatar_etag' ],
  fnOrTable: 'etags',
  foreignColumns: [ 'storage_id', 'id' ],
  options: {
    name: undefined,
    match: undefined,
    onUpdate: 'CASCADE',
    onDelete: 'SET NULL'
  }
}
```

I believe the error is because `options.name` and `options.match` are undefined. Let me know if you need anymore info.

Schema:

```sql
CREATE TABLE public.accounts (
    id text NOT NULL,
    public_key text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    alias text,
    bio text DEFAULT ''::text NOT NULL,
    avatar_storage_id public."Storage",
    avatar_etag text,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_seen_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_verified boolean DEFAULT false NOT NULL
);

CREATE TABLE public.etags (
    storage_id public."Storage" NOT NULL,
    id text NOT NULL,
    type text NOT NULL,
    num_posts_attached integer DEFAULT 0 NOT NULL,
    num_avatars_attached integer DEFAULT 0 NOT NULL,
    num_pass_collection_avatars_attached integer DEFAULT 0 NOT NULL,
    num_covers_attached integer DEFAULT 0 NOT NULL,
    static boolean DEFAULT false NOT NULL
);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_avatar_storage_id_avatar_etag_fkey FOREIGN KEY (avatar_storage_id, avatar_etag) REFERENCES public.etags(storage_id, id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE TYPE public."Storage" AS ENUM (
    'r2'
);
```

**Comment by romeerez** [comment]
Thank you for the detailed info.

The bug is fixed, and the packages updated.
