### ISSUE TITLE
tables[key] is not a constructor

### ISSUE THREAD

**Issue by leifniem** [romeerez/orchid-orm#49]
Hi and first off thanks and props for this project, the docs are more in depth than a lot i've seen in a while 👍 

I wanted to get a basic experiment running by generating a project with the quick start guide and after a clean run of `db pull` imported the `db`. No matter if i ran a basic query or just tried to log the `db` object to console, i ran into the following error:

```
> server@1.0.0 dev C:\Users\Leif\dev\orchid-test\server
> ts-node src/index.ts

C:\Users\Leif\dev\orchid-test\node_modules\.pnpm\orchid-orm@1.6.38_typescript@5.0.3\node_modules\orchid-orm\src\orm.ts:74
    const table = new tables[key]();
                  ^
TypeError: tables[key] is not a constructor
    at orchidORM (C:\Users\Leif\dev\orchid-test\node_modules\.pnpm\orchid-orm@1.6.38_typescript@5.0.3\node_modules\orchid-orm\src\orm.ts:74:19)
    at Object.<anonymous> (C:\Users\Leif\dev\orchid-test\server\src\db\db.ts:52:28)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module.m._compile (C:\Users\Leif\dev\orchid-test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.46_@types+node@18.15.11_typescript@5.0.3\node_modules\ts-node\src\ind
ex.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Leif\dev\orchid-test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.46_@types+node@18.15.11_typescript@5.0.3\
node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Function.Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
```

The project is using pnpm workspaces, but i tried installing with npm directly in the folder and received the same error message.

Should you need the code to debug i'll see that i reduce it to a minimum since it's cluttered with docker stuff at the moment.

**Comment by leifniem** [comment]
It was related to me forgetting to delete my manually created `schemamigrations` table, which confused the client. Sorry, my bad.

**Comment by romeerez** [comment]
Are you sure there is no bug? Because the error looks suspicious. If no bug then cool.
